# https://gohugo.io/variables/site/

baseURL = "https://blog.kpping.me"
copyright = "kpping"
disqusShortname = "blog-kpping-me"
enableRobotsTXT = true
relativeURLs = true
title = "blog.kpping.me"

[params]
  author = "kpping"
  description = "My simple micro blog."
  homepageKeywords = ["blog.kpping.me", "blog", "kpping"]
  logo = "/apple-icon-114x114.png"
