baseURL = "https://blog.kpping.me"
relativeURLs = true
languageCode = "th"
title = "blog.kpping.me"
theme = "blank"
enableRobotsTXT = true

[params]
  author = "kpping"
  description = "My simple micro blog."